import './styles/global.css'; import { FlappyGame } from './game/FlappyGame'; import { GameRenderer } from './renderer/GameRenderer'; import { BrainRenderer } from './renderer/BrainRenderer'; import { FlyBrain } from './brain/FlyBrain'; import { FlyEncoder } from './brain/FlyEncoder'; import { loadManifest } from './brain/BrainLoader'; import { ExperimentHistory } from './experiment/ExperimentHistory'; import type { AppState, BrainActivity, BrainResult, Mode } from './types';
const empty:BrainActivity={lc4:0,lplc2:0,lc10Left:0,lc10Right:0,upward:0,downward:0,dnp01:0};
export class App {
  private state:AppState='BOOT'; private mode:Mode='online'; private slow=false; private autoRevive=false; private flyId=ExperimentHistory.nextFlyId(); private seed=Number(new URLSearchParams(location.search).get('seed'))||Date.now();
  private game!:FlappyGame; private brain!:FlyBrain; private gameRenderer!:GameRenderer; private brainRenderer!:BrainRenderer;private activity=empty;private result?:BrainResult;private last=performance.now();private brainClock=0;private renderClock=0;private fps=60;private frames=0;private fpsAt=performance.now();private latency=0;private autoTimer=0;
  constructor(private root:HTMLElement){this.paint();this.bind();void this.boot()}
  private paint(){this.root.innerHTML=`<main><header><div><div class="eyebrow">生物计算 · 实验 #01 / BIOLOGICAL COMPUTATION</div><h1><span>🪰</span> 一颗果蝇大脑 <em>挑战 Flappy Bird</em></h1><p>真实的果蝇连接组，去做不可能的事。</p></div><div class="facts"><b>166,700 <small>神经元</small></b><b>~25.6M <small>连接</small></b><b class="frozen">● 连接组已冻结 <small>FROZEN</small></b></div></header>
  <section class="workspace"><article class="panel brain"><div class="panel-title"><span>01 / 果蝇大脑</span><i>实时活动</i></div><canvas id="brain"></canvas><div class="brain-meta"><strong>166,700</strong><span>神经元活动热力图<br>WEBGL / ${crossOriginIsolated?'共享内存 SHARED':'传输缓冲 TRANSFER'}</span></div><div id="sequence" class="sequence">等待感觉输入…</div></article>
  <article class="panel game"><div class="panel-title"><span>02 / 飞行竞技场</span><i id="flyLabel">FLY #${this.flyId} · 第 ${this.flyId} 只果蝇</i></div><div class="canvas-wrap"><canvas id="game"></canvas><div id="death" class="death hidden"></div></div></article>
  <article class="panel data"><div class="panel-title"><span>03 / 神经数据</span><i>50 HZ</i></div><h2>视觉输入</h2><div id="sensors"></div><h2>运动输出</h2><div id="motor"></div><div class="decision"><small>决策</small><strong id="decision">· 待命</strong><span id="prob"></span></div><h2>本机最佳 <small>此浏览器</small></h2><ol id="leaders"></ol></article></section>
  <section class="status"><div><small>当前分</small><b id="score">0</b></div><div><small>最高分</small><b id="best">${ExperimentHistory.best()}</b></div><div><small>游戏</small><b id="fps">60 FPS</b></div><div><small>大脑</small><b>50 HZ</b></div><div><small>步进</small><b id="step">— 毫秒</b></div><div><small>模式</small><b id="modeLabel">学习中</b></div></section>
  <nav><div class="mode"><button id="pure">纯大脑</button><button id="trained" class="active">边玩边学</button></div><button id="fastTrain">⚡ 速训模型</button><button id="exportModel">导出模型</button><button id="importModel">导入模型</button><input id="modelFile" class="hidden" type="file" accept="application/json,.json"><button id="slow">慢速大脑</button><label><input id="auto" type="checkbox"> 自动复活</label><button id="restart">重置</button></nav>
  <footer><strong>科学说明</strong><p>连接组来自 MaleCNS v1.0 果蝇神经连接数据集（CC BY 4.0）。Flappy Bird 的视觉编码与运动解码是人工实验接口，连接组本身保持冻结。</p></footer></main><div id="training" class="training hidden"><div><div class="eyebrow">冻结连接组 · 仅训练读出层</div><h2>速训模型</h2><p id="trainText">正在生成教师样本…</p><div class="track"><i id="trainBar"></i></div><b id="trainPct">0%</b></div></div><div id="toast" class="toast hidden"></div><div id="loading" class="loading"><div class="loader-card"><div class="fly-icon">🪰</div><div class="eyebrow">正在初始化生物神经网络</div><h2>载入中<br>果蝇大脑…</h2><div class="load-stat"><span id="loadText">定位连接组…</span><b id="loadPct">0%</b></div><div class="track"><i id="loadBar"></i></div><div class="online"><span>166,700 神经元</span><span>25,088,107 有效连接</span></div><button id="wake" class="hidden">唤醒果蝇 →</button><div id="loadError" class="load-error"></div></div></div>`}
  private bind(){this.gameRenderer=new GameRenderer(this.$('game'));this.brainRenderer=new BrainRenderer(this.$('brain'));this.game=new FlappyGame(this.seed,(cause)=>this.die(cause));this.$b('pure').onclick=()=>this.setMode('pure');this.$b('trained').onclick=()=>this.setMode('online');this.$b('fastTrain').onclick=()=>this.fastTrain();this.$b('exportModel').onclick=()=>this.exportModel();this.$b('importModel').onclick=()=>this.$<HTMLInputElement>('modelFile').click();this.$<HTMLInputElement>('modelFile').onchange=e=>void this.importModel((e.target as HTMLInputElement).files?.[0]);this.$b('slow').onclick=()=>{this.slow=!this.slow;this.$b('slow').classList.toggle('active',this.slow)};this.$b('restart').onclick=()=>this.restart();this.$<HTMLInputElement>('auto').onchange=e=>this.autoRevive=(e.target as HTMLInputElement).checked;this.$b('wake').onclick=()=>this.start()}
  private async boot(){this.state='LOADING_CONNECTOME';try{const manifest=await loadManifest(p=>this.progress(p.value,p.label));this.brain=new FlyBrain();this.brain.onProgress=(v,l)=>this.progress(v,l);this.brain.onResult=r=>this.onBrain(r);this.brain.onTrainingProgress=(done,total,loss)=>this.trainingProgress(done,total,loss);this.brain.onTrainingDone=(model,samples,loss)=>this.trainingDone(model,samples,loss);let saved:unknown;try{saved=JSON.parse(localStorage.getItem('fly-readout-online-v1')??'null')}catch{saved=undefined}await this.brain.init(manifest,saved);this.progress(1,'连接组就绪 · 大脑上线');this.state='READY';this.$b('wake').classList.remove('hidden')}catch(error){this.state='ERROR';this.$('loadError').innerHTML=`<b>连接组不可用</b><p>${error instanceof Error?error.message:String(error)}</p><p>请把已校验的 fly.ai 浏览器导出文件放进 <code>public/brain/</code>，然后刷新页面。系统不做任何模拟回退。</p>`}}
  private start(){if(this.state==='ERROR')return;this.state='RUNNING';this.$('loading').classList.add('hidden');this.game.start();this.last=performance.now();requestAnimationFrame(t=>this.loop(t))}
  private loop(now:number){if(this.state!=='RUNNING')return;const scale=this.slow?.1:1,dt=Math.min(.033,(now-this.last)/1000)*scale;this.last=now;this.game.update(dt);this.brainClock+=dt;while(this.brainClock>=.02){this.brainClock-=.02;this.brain.step(this.game.capture(),this.mode,this.game.elapsed)}const s=FlyEncoder.encode(this.game.capture());this.gameRenderer.render(this.game,s.lc4);if(now-this.renderClock>=(this.slow?100:40)){this.brainRenderer.render(this.brain.activity??new Uint8Array(this.result?.activityFrame??new ArrayBuffer(8192)));this.renderClock=now}this.updateHud();this.frames++;if(now-this.fpsAt>=1000){this.fps=this.frames*1000/(now-this.fpsAt);this.frames=0;this.fpsAt=now}requestAnimationFrame(t=>this.loop(t))}
  private onBrain(r:BrainResult){this.latency=performance.now()-r.timestamp;this.result=r;this.activity=r.activity;if(r.readoutModel&&this.mode==='online')localStorage.setItem('fly-readout-online-v1',JSON.stringify(r.readoutModel));if(r.decision==='FLAP')this.game.flap();this.renderData(r)}
  private die(cause:string){if(this.state!=='RUNNING')return;this.state='DEAD';const rec={flyId:this.flyId,mode:this.mode,score:this.game.score,lifetime:this.game.elapsed,totalSpikes:this.result?.totalSpikes??0,at:Date.now()};ExperimentHistory.add(rec);const d=this.$('death');d.classList.remove('hidden');d.innerHTML=`<small>实验终止</small><h2>果蝇 #${this.flyId} 阵亡</h2><div class="death-grid"><span>分数<b>${this.game.score} 管</b></span><span>存活<b>${this.game.elapsed.toFixed(1)} 秒</b></span><span>总放电<b>${(this.result?.totalSpikes??0).toLocaleString()} 次</b></span></div><h3>死因 <i>娱乐向</i></h3><p>${cause}</p><button id="revive">复活果蝇 →</button>`;(d.querySelector('#revive') as HTMLButtonElement).onclick=()=>this.restart();this.renderLeaders();if(this.autoRevive)this.autoTimer=window.setTimeout(()=>this.restart(),2000)}
  private restart(){clearTimeout(this.autoTimer);this.flyId++;this.seed++;this.game.reset(this.seed);this.brain?.reset(this.seed);this.result=undefined;this.activity=empty;this.$('death').classList.add('hidden');this.$('flyLabel').textContent=`FLY #${this.flyId} · 第 ${this.flyId} 只果蝇`;if(this.state==='READY')this.start();else{this.state='RUNNING';this.game.start();this.last=performance.now();requestAnimationFrame(t=>this.loop(t))}}
  private setMode(mode:Mode){this.mode=mode;this.$b('pure').classList.toggle('active',mode==='pure');this.$b('trained').classList.toggle('active',mode==='online');this.$b('fastTrain').classList.toggle('active',mode==='trained');this.$('modeLabel').textContent=mode==='pure'?'纯大脑':mode==='online'?'学习中':'速训模型';this.renderData(this.result)}
  private renderData(r?:BrainResult){const a=r?.activity??this.activity;this.$('sensors').innerHTML=[['LC4',a.lc4],['LPLC2',a.lplc2],['LC10a-L',a.lc10Left],['LC10a-R',a.lc10Right],['UPWARD',a.upward],['DOWNWARD',a.downward]].map(([n,v])=>this.meter(String(n),Number(v))).join('');this.$('motor').innerHTML=this.meter('DNp01',a.dnp01);const flap=r?.decision==='FLAP';this.$('decision').textContent=flap?'↑ 拍翅':'· 待命';this.$('decision').classList.toggle('flap',flap);this.$('prob').textContent=this.mode!=='pure'?`拍翅概率 ${Math.round((r?.flapProbability??0)*100)}% · 已学 ${r?.trainingSamples??0} 样本 · 损失 ${(r?.trainingLoss??0).toFixed(3)}`:'100 ms 需 2 次峰 · 冷却 120 ms';this.$('sequence').textContent=this.slow?(a.lc4>.1?(a.dnp01>.2?'下行神经元激活 → 发出运动信号':'感觉输入已检出 → 神经信号正在传导…'):'等待感觉输入…'):'实时放电图谱';this.$('step').textContent=`${(r?.stepTime??0).toFixed(1)} 毫秒`}
  private meter(name:string,value:number){return `<div class="meter"><div><b>${name}</b><span>${Math.round(value*100)}%</span></div><i><em style="width:${value*100}%"></em></i></div>`}
  private updateHud(){this.$('score').textContent=String(this.game.score);this.$('best').textContent=String(Math.max(this.game.score,ExperimentHistory.best()));this.$('fps').textContent=`${Math.round(this.fps)} FPS`;if(location.search.includes('debug=1'))this.$('sequence').title=`worker latency ${this.latency.toFixed(2)} ms`}
  private renderLeaders(){const rows=ExperimentHistory.leaders();this.$('leaders').innerHTML=rows.length?rows.map((r,i)=>`<li><span>#${i+1} 第 ${String(r.flyId).padStart(3,'0')} 只果蝇</span><b>${r.score} 管</b></li>`).join(''):'<li><span>暂无完成的飞行</span><b>—</b></li>'}
  private fastTrain(){if(!this.brain||this.state==='LOADING_CONNECTOME'||this.state==='ERROR')return;this.game.stop();this.setMode('trained');this.$('training').classList.remove('hidden');this.$b('fastTrain').disabled=true;this.brain.fastTrain(1200)}
  private trainingProgress(done:number,total:number,loss:number){const value=done/total;this.$('trainBar').style.width=`${value*100}%`;this.$('trainPct').textContent=`${Math.round(value*100)}%`;this.$('trainText').textContent=`${done.toLocaleString()} / ${total.toLocaleString()} 神经样本 · 损失 ${loss.toFixed(3)}`}
  private trainingDone(model:unknown,samples:number,loss:number){localStorage.setItem('fly-readout-fast-v1',JSON.stringify(model));this.$('training').classList.add('hidden');this.$b('fastTrain').disabled=false;if(this.state==='RUNNING')this.game.start();this.toast(`模型就绪 · ${samples.toLocaleString()} 样本 · 损失 ${loss.toFixed(3)}`)}
  private exportModel(){const key=this.mode==='online'?'fly-readout-online-v1':'fly-readout-fast-v1',raw=localStorage.getItem(key);if(!raw){this.toast('还没有训练好的模型');return}const model={format:'fly-brain-readout-v3',exportedAt:new Date().toISOString(),model:JSON.parse(raw)};const url=URL.createObjectURL(new Blob([JSON.stringify(model,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`fly-readout-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(url);this.toast('模型已导出')}
  private async importModel(file?:File){if(!file)return;try{const parsed=JSON.parse(await file.text()),model=parsed.format?.startsWith('fly-brain-readout-v')?parsed.model:parsed;if(!Array.isArray(model?.features)||!Array.isArray(model?.weights)||model.features.length!==model.weights.length)throw new Error('模型结构不兼容');this.setMode('trained');this.brain.importModel(model);this.$<HTMLInputElement>('modelFile').value=''}catch(error){this.toast(`导入失败 · ${error instanceof Error?error.message:'文件无效'}`)}}
  private toast(message:string){const el=this.$('toast');el.textContent=message;el.classList.remove('hidden');window.setTimeout(()=>el.classList.add('hidden'),2600)}
  private progress(v:number,label:string){this.$('loadBar').style.width=`${v*100}%`;this.$('loadPct').textContent=`${Math.round(v*100)}%`;this.$('loadText').textContent=label}
  private $<T extends HTMLElement=HTMLElement>(id:string){return document.getElementById(id) as T} private $b(id:string){return this.$<HTMLButtonElement>(id)}
}
